# Generated by Django 3.1.7 on 2021-05-19 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0002_auto_20210519_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_det_new',
            name='time_rec',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 9, 53, 22, 53429, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_det_new',
            name='time_rec',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 9, 53, 25, 92425, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsaved_new',
            name='time_rec',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 9, 53, 27, 254225, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsaved_purchase_new',
            name='time_rec',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 9, 53, 29, 156379, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
