# Generated by Django 3.1.7 on 2021-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_det_new',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporary_new',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=25),
        ),
        migrations.AddField(
            model_name='temporary_new',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporary_purchase_new',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction_det_new',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=25),
        ),
        migrations.AddField(
            model_name='transaction_det_new',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unsaved_new',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=25),
        ),
        migrations.AddField(
            model_name='unsaved_new',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unsaved_purchase_new',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
