# Generated by Django 3.1.7 on 2021-06-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0005_auto_20210624_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_diary_new',
            name='seq_id',
        ),
    ]
