# Generated by Django 3.1.7 on 2021-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0008_auto_20210625_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_diary_new',
            name='seq_id',
        ),
    ]
