# Generated by Django 3.1.7 on 2021-06-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0014_auto_20210625_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_cards',
            name='description',
        ),
    ]
