# Generated by Django 3.1.7 on 2021-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0015_remove_purchase_cards_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_ca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('ss_code', models.CharField(max_length=200)),
                ('carbs', models.CharField(max_length=200)),
                ('protein', models.CharField(max_length=200)),
                ('fat', models.CharField(max_length=200)),
                ('fiber', models.CharField(max_length=200)),
                ('sugar', models.CharField(max_length=200)),
                ('sodium', models.CharField(max_length=200)),
                ('alchohol', models.CharField(max_length=200)),
                ('calorie', models.CharField(max_length=200)),
                ('calorie_saturated_fats', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=400)),
                ('image_path', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='purchase_cards',
        ),
    ]
