# Generated by Django 3.1.7 on 2021-06-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0016_auto_20210625_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_ca',
            new_name='purchase_cards',
        ),
    ]
