# Generated by Django 3.1.7 on 2021-06-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0017_auto_20210625_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_cards',
            name='calorie_saturated_fats',
        ),
    ]
