# Generated by Django 3.1.7 on 2021-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0019_purchase_cards_calorie_saturated_fats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_cards',
            old_name='alchohol',
            new_name='alcohol',
        ),
        migrations.AddField(
            model_name='purchase_det_new',
            name='shop_name',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporary_purchase_new',
            name='shop_name',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsaved_purchase_new',
            name='shop_name',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
    ]
