# Generated by Django 3.1.7 on 2021-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0021_purchase_cards_seq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_code', models.CharField(blank=True, max_length=10, null=True)),
                ('food_id', models.CharField(blank=True, max_length=10, null=True)),
                ('food_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('food_type', models.CharField(blank=True, max_length=200, null=True)),
                ('calories', models.CharField(blank=True, max_length=10, null=True)),
                ('fats', models.CharField(blank=True, max_length=10, null=True)),
                ('protein', models.CharField(blank=True, max_length=10, null=True)),
                ('carbohydrates', models.CharField(blank=True, max_length=10, null=True)),
                ('link_of_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_of_recipie', models.CharField(blank=True, max_length=1000, null=True)),
                ('purchasing_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'basic_app_food_diary',
                'managed': False,
            },
        ),
    ]
