# Generated by Django 3.1.7 on 2021-07-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0022_food_diary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_diary',
            options={},
        ),
    ]
