# Generated by Django 3.1.7 on 2021-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0024_auto_20210714_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_Food_Diary',
            fields=[
                ('mfg_code', models.CharField(blank=True, max_length=10, null=True)),
                ('food_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('food_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('food_type', models.CharField(blank=True, max_length=200, null=True)),
                ('calories', models.CharField(blank=True, max_length=10, null=True)),
                ('fats', models.CharField(blank=True, max_length=10, null=True)),
                ('protein', models.CharField(blank=True, max_length=10, null=True)),
                ('carbohydrates', models.CharField(blank=True, max_length=10, null=True)),
                ('link_of_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_of_recipie', models.CharField(blank=True, max_length=1000, null=True)),
                ('purchasing_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Food_Diary_Old',
        ),
    ]
