# Generated by Django 3.1.7 on 2021-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0025_auto_20210714_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine_consumption_det',
            fields=[
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_rec', models.TimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('food_id', models.CharField(default='null', max_length=10)),
                ('food_name', models.CharField(blank=True, max_length=50, null=True)),
                ('food_type', models.CharField(blank=True, max_length=200, null=True)),
                ('calories', models.CharField(blank=True, max_length=10, null=True)),
                ('fats', models.CharField(blank=True, max_length=10, null=True)),
                ('protein', models.CharField(blank=True, max_length=10, null=True)),
                ('carbohydrates', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuisine_consumption_temp',
            fields=[
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_rec', models.TimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('food_id', models.CharField(default='null', max_length=10)),
                ('food_name', models.CharField(blank=True, max_length=50, null=True)),
                ('food_type', models.CharField(blank=True, max_length=200, null=True)),
                ('calories', models.CharField(blank=True, max_length=10, null=True)),
                ('fats', models.CharField(blank=True, max_length=10, null=True)),
                ('protein', models.CharField(blank=True, max_length=10, null=True)),
                ('carbohydrates', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
