# Generated by Django 3.1.7 on 2021-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0026_cuisine_consumption_det_cuisine_consumption_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine_consumption_det',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuisine_consumption_temp',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
