# Generated by Django 3.1.7 on 2021-07-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0027_auto_20210715_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine_consumption_det',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=25),
        ),
        migrations.AddField(
            model_name='cuisine_consumption_temp',
            name='meal_type',
            field=models.CharField(default='Breakfast', max_length=25),
        ),
    ]
