# Generated by Django 3.1.7 on 2021-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app_new', '0028_auto_20210715_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine_consumption_det',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='cuisine_consumption_temp',
            name='cid',
        ),
        migrations.AlterField(
            model_name='old_food_diary',
            name='food_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
